map_server:
  ros__parameters:
    frame_id: "map"

corridor_generator:
  ros__parameters:
    robot_clearance: 0.3

# For unicycle
corridor_planner:
  ros__parameters:
    v_max: 0.5
    omega_max: 2.0
    robot_width: 0.34
    robot_length: 0.237
    model_type: "unicycle"
    sampling_dt: 0.100
    map_frame: "map"

# For bicycle
# corridor_planner:
#   ros__parameters:
#     v_max: 1.0
#     robot_delta_max: 0.5
#     robot_width: 0.430
#     robot_length: 0.508
#     model_type: "bicycle"
#     sampling_dt: 0.100
#     map_frame: "map"