planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["NavFn", "SmacHybrid", "SmacLattice"]
    
    NavFn:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.1
      use_astar: true
      allow_unknown: true
      
    SmacHybrid:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      tolerance: 0.1
      downsample_costmap: false
      downsampling_factor: 1
      allow_unknown: true
      max_iterations: 1000000
      max_planning_time: 5.0
      motion_model_for_search: "REEDS_SHEPP"
      angle_quantization_bins: 72
      analytic_expansion_ratio: 3.5
      minimum_turning_radius: 0.25
      reverse_penalty: 2.0
      change_penalty: 0.0
      non_straight_penalty: 1.2
      cost_penalty: 2.0
      retrospective_penalty: 0.015
      lookup_table_size: 20.0
      cache_obstacle_heuristic: false
      
    SmacLattice:
      plugin: "nav2_smac_planner::SmacPlannerLattice"
      tolerance: 0.1
      allow_unknown: true
      max_iterations: 1000000
      max_planning_time: 5.0
      analytic_expansion_ratio: 3.5
      reverse_penalty: 2.0
      change_penalty: 0.05
      non_straight_penalty: 1.05
      cost_penalty: 2.0
      rotation_penalty: 5.0
      retrospective_penalty: 0.015
      lookup_table_size: 20.0
      cache_obstacle_heuristic: false